apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insights-rules-statistics
spec:
  destination:
    namespace: aiops-prod-argo
    server: https://api.ocp4.prod.psi.redhat.com:6443
  project: ccx
  source:
    path: manifests
    repoURL: https://gitlab.cee.redhat.com/psilling/insights-rules-statistics.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
