apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: argocd-repo-server
          env:
            - name: ARGOCD_EXEC_TIMEOUT
              value: "300"
