---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        image: quay.io/aicoe/argocd:v1.7.4-3
        resources:
          limits:
            memory: 8Gi
