apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-redis
    spec:
      containers:
      - image: quay.io/internaldatahub/redis:5.0.8
        name: redis
