apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aicoe-argocd
resources:
- ../../base
- projects
- applications
configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - configs/argo_cm/dex.config
  - configs/argo_cm/kustomize.buildOptions
  - configs/argo_cm/repositories
  - configs/argo_cm/resource.exclusions
  - configs/argo_cm/resource.inclusions
  - configs/argo_cm/url
- name: argocd-rbac-cm
  behavior: replace
  files:
  - configs/argo_rbac_cm/policy.csv
generatorOptions:
  disableNameSuffixHash: true
generators:
- secrets/gpg/secret-generator.yaml
- secrets/auth/secret-generator.yaml
- secrets/clusters/secret-generator.yaml
patchesStrategicMerge:
- serviceaccounts/argocd-dex-server.yaml
