apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-cd/manifests/base?ref=v1.6.1
- resources/routes/argocd_server_route.yaml
- resources/serviceaccounts/argocd-manager.yaml
patchesStrategicMerge:
- resources/services/argocd_metrics_service_patch.yaml
- resources/services/argocd_server_metrics_service_patch.yaml
- resources/deployments/argocd-repo-server_patch.yaml
- resources/deployments/argocd-server_patch.yaml
