apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-role-binding
roleRef:
  name: argocd-manager-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: argocd-manager
  kind: ServiceAccount
