---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thoth-qeb-hwt
spec:
  project: thoth
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: qeb-hwt-github-app/overlays/ocp
    targetRevision: HEAD
  destination:
    server: 'https://api.ocp.prod.psi.redhat.com:6443'
    namespace: aicoe-prod-bots
  syncPolicy:
    automated: {}
