---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-argocd-customization
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/AICoE/argocd-customization
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: quay.io/aicoe/argocd:v1.5.2-1
        - name: TLSVERIFY
          value: "false"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-aicoe-argocd-customization
spec:
  pipelineRef:
    name: buildah-argocd-customization
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: buildah-source-pvc
