---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-aicoe-argocd-customization
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/kelseyhightower/nocode
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: localhost:5000/nocode
        - name: TLSVERIFY
          value: "false"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-aicoe-argocd-customization-
spec:
  pipelineRef:
    name: build-aicoe-argocd-customization
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: buildah-source-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: buildah-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
