---
- name: Deploy ArgoCD to Openshift
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Ensure that the target_env variable is set
      fail:
        msg: "target_env variable must be set"
      when: "target_env is undefined"

    - name: Load the common vars file
      include_vars:
        file: "vars/common-vars.yaml"

    - name: Load the appropriate vars file
      include_vars:
        file: "vars/{{ target_env }}-vars.yaml"

    - name: Load gpg key
      include_vars:
        file: "vars/gpg-keys/{{ target_env}}-key.yaml"

    - name: Ensure that the required variables are set
      fail:
        msg: "Required variable '{{ item }}' was not found"
      when: "{{ item }} is undefined"
      with_items:
        - kubeconfig
        - namespace
        - gpg_key
        - repo_server_image

    - name: Verify namespace exists
      k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        verify_ssl: no
      when: target_env == 'dev'

    - name: Deploy the ArgoCD objects to Openshift
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ namespace }}"
        verify_ssl: no
        definition: "{{ lookup('template', item) }}"
      with_items:
        - objects/secret.yaml
        - objects/namespace-install.yaml
        - objects/argocd_server_route.yaml

    - name: Patch ArgoCD admin psw
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ namespace }}"
        verify_ssl: no
        definition: "{{ lookup('template', item ) }}"
        merge_type:
        - merge
      with_items:
        - objects/admin_creds_patch.yaml