apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aicoe-argocd
spec:
  destination:
    name: api.ocp4.prod.psi.redhat.com
    namespace: aicoe-argocd
  project: data-hub
  source:
    path: manifests/overlays/prod
    repoURL: https://github.com/AICoE/aicoe-cd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
