apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo.dh-prod-argo
spec:
  destination:
    namespace: dh-prod-argo
    server: https://datahub.psi.redhat.com:443
  project: data-hub
  source:
    path: argo/overlays/dh-prod-argo
    repoURL: https://github.com/AICoE/idh-manifests.git
    targetRevision: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows.dh-prod-argo
spec:
  destination:
    namespace: dh-prod-argo
    server: https://datahub.psi.redhat.com:443
  project: data-hub
  source:
    path: argo-workflows/overlays/prod
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false