apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-alertmanager.dh-psi-monitoring
spec:
  destination:
    name: api.ocp4.prod.psi.redhat.com
    namespace: dh-psi-monitoring
  project: data-hub
  source:
    path: prometheus/overlays/prod/
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - Validate=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana.dh-psi-monitoring
spec:
  destination:
    name: api.ocp4.prod.psi.redhat.com
    namespace: dh-psi-monitoring
  project: data-hub
  source:
    path: grafana/prod/
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - Validate=false
  ignoreDifferences:
  - kind: Secret
    name: default-ingress-cert
    namespace: dh-psi-monitoring
    jsonPointers:
    - /metadata/labels
