apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-prod-s3-webserver
spec:
  destination:
    namespace: dh-prod-s3-webserver
    server: https://api.datahub-ocp4.prod.psi.redhat.com:6443
  project: data-hub
  source:
    path: s3-webserver/overlays/prod
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
