apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-psi-monitoring
spec:
  destination:
    name: api.ocp4.prod.psi.redhat.com
    namespace: dh-psi-monitoring
  project: data-hub
  source:
    path: monitoring/psi-prod-cluster/overlays/prod
    repoURL: https://github.com/AICoE/idh-manifests.git
    targetRevision: production
  syncPolicy:
    syncOptions:
    - Validate=false
