apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-prod-kafka
spec:
  destination:
    namespace: dh-prod-message-bus
    server: 'https://datahub.psi.redhat.com:443'
  project: data-hub
  source:
    path: kafka
    repoURL: https://github.com/AICoE/idh-manifests.git
    targetRevision: production
    plugin:
      name: helmSecrets
      env:
        - name: VALUES_FILES
          value: "-f secrets.enc.yaml -f helm_vars/prod/secrets.yaml -f helm_vars/prod/values.yaml"
  syncPolicy:
    automated: {}
    syncOptions:
      - Validate=false
