apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-prod-superset
spec:
  destination:
    namespace: dh-prod-superset
    server: 'https://datahub.psi.redhat.com:443'
  project: data-hub
  source:
    path: kfdefs/overlays/prod/dh-prod-superset
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Validate=false
