apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-prod-trino
spec:
  destination:
    namespace: dh-prod-trino
    server: https://api.ocp4.prod.psi.redhat.com:6443
  project: data-hub
  source:
    path: kfdefs/overlays/prod/dh-prod-trino
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Validate=false
