apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-prod-data-catalog-ccx
spec:
  destination:
    namespace: dh-prod-data-catalog-ccx
    server: https://datahub.psi.redhat.com:443
  project: data-hub
  source:
    path: data-catalog/overlays/prod-ccx
    repoURL: https://github.com/AICoE/idh-manifests.git
    targetRevision: production
  syncPolicy:
    syncOptions:
    - Validate=false
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: hue-mysql
    jsonPointers:
    - /spec/template/spec/containers/0/image
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: thriftserver
    jsonPointers:
    - /spec/template/spec/initContainers/0/image
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: thriftserver-postgres
    jsonPointers:
    - /spec/template/spec/containers/1/image
