apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-stage-rhods-catalog
spec:
  destination:
    namespace: openshift-marketplace
    server: https://api.rhods-idh.dev.datahub.redhat.com:6443
  project: data-hub
  source:
    path: rhods/catalog-source/overlays/stage
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
    automated: {}
