apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-stage-analytics-factory
spec:
  destination:
    namespace: dh-stage-analytics-factory
    server: 'https://paas.stage.psi.redhat.com:443'
  project: data-hub
  source:
    path: data-catalog/overlays/stage
    repoURL: https://github.com/AICoE/idh-manifests.git
    targetRevision: production
  syncPolicy:
    syncOptions:
    - Validate=false
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: hue-mysql
    jsonPointers:
    - /spec/template/spec/containers/0/image
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: thriftserver
    jsonPointers:
    - /spec/template/spec/initContainers/0/image
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: thriftserver-postgres
    jsonPointers:
    - /spec/template/spec/containers/1/image
