apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-stage-trino
spec:
  destination:
    namespace: dh-stage-trino
    server: 'https://api.idh-stage.dev.datahub.redhat.com:6443'
  project: data-hub
  source:
    path: kfdefs/overlays/stage/dh-stage-trino
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
