apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dh-stage-superset
spec:
  destination:
    namespace: dh-stage-superset
    server: 'https://paas.stage.psi.redhat.com:443'
  project: data-hub
  source:
    path: kfdefs/overlays/stage/dh-stage-trino
    repoURL: https://github.com/AICoE/internal-data-hub.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
