apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dh-prod-jupyterhub.yaml
- dh-psi-monitoring.yaml
- dh-prod-kafka.yaml
- dh-stage-jupyterhub.yaml
- dh-stage-kafka.yaml
- dh-stage-rsyslog.yaml
- dh-prod-rsyslog.yaml
- dh-stage-logstash.yaml
- dh-prod-logstash.yaml
- dh-stage-analytics-factory.yaml
- dh-prod-analytics-factory.yaml
- dh-prod-data-catalog-ccx.yaml
- dh-prod-data-catalog-usir.yaml
- dh-stage-superset.yaml
- dh-prod-superset.yaml
- dh-stage-argo.yaml
# - dh-prod-argo.yaml  # FIXME: Unlisted until dh-stage-argo verifies the migration success
