kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: '--enable_alpha_plugins'
  repositories: |
    - type: git
      url: https://github.com/goern/strimzi-application.git
    - type: git
      url: https://github.com/goern/thoth-application.git
    - type: git
      url: https://github.com/thoth-station/thoth-application.git
    - type: git
      url: https://github.com/thoth-station/thoth-ci.git
  resource.exclusions: |
    - apiGroups:
      - "tekton.dev/v1alpha1"
      kinds:
      - "PipelineRun"
      - "TaskRun"
      clusters:
      - "*"
