namespace: aicoe-argocd
# ArgoCD admin passwords are bcrypted (hashed).
# You can (ab)use `htpasswd -bnBC 10 "" <password>` to generate a password
# from cmd line using bcrypt function (-B).
admin_password: "$2y$10$18l2wN8YokC8rghRWbrhlu4kXCP7P9oJ7L45GHJ4RWsSR7zKXmnXy"
repo_server_image: quay.io/aicoe/argocd:v1.5.2-1
argo_cm: |
  data:
    url: {{ argocd_url }}
    dex.config: |
      connectors:
        # OpenShift
        - type: openshift
          id: openshift
          name: OpenShift
          config:
            issuer: {{ issuer }}
            clientID: {{ clientID }}
            clientSecret: {{ clientSecret }}
            redirectURI: {{ redirectURI }}
            insecureCA: true
            groups:
              - data-hub-openshift-admins
              - aicoe-thoth-devops
    kustomize.buildOptions: "--enable_alpha_plugins"
    repositories: |
      - type: git
        url: https://github.com/goern/strimzi-application.git
      - type: git
        url: https://github.com/goern/thoth-application.git
      - type: git
        url: https://github.com/thoth-station/thoth-application.git
      - type: git
        url: https://github.com/thoth-station/thoth-ci.git
    resource.exclusions: |
      - apiGroups:
        - "tekton.dev/v1beta1"
        kinds:
        - "PipelineRun"
        - "TaskRun"
        clusters:
        - "*"
