namespace: aicoe-argocd
# ArgoCD admin passwords are bcrypted (hashed).
# You can (ab)use `htpasswd -bnBC 10 "" <password>` to generate a password
# from cmd line using bcrypt function (-B).
admin_password: "$2y$10$18l2wN8YokC8rghRWbrhlu4kXCP7P9oJ7L45GHJ4RWsSR7zKXmnXy"
repo_server_image: quay.io/aicoe/argocd:v1.5.2-1
argo_cm: |
  data:
    url: {{ argocd_url }}
    dex.config: |
      connectors:
        # OpenShift
        - type: openshift
          id: openshift
          name: OpenShift
          config:
            issuer: {{ issuer }}
            clientID: {{ clientID }}
            clientSecret: {{ clientSecret }}
            redirectURI: {{ redirectURI }}
            insecureCA: true
            groups:
              - data-hub-openshift-admins
              - aicoe-thoth-devops
    kustomize.buildOptions: "--enable_alpha_plugins"
    repositories: |
      - type: git
        url: https://github.com/goern/strimzi-application.git
      - type: git
        url: https://github.com/goern/thoth-application.git
      - type: git
        url: https://github.com/thoth-station/thoth-application.git
      - type: git
        url: https://github.com/thoth-station/thoth-ci.git
    resource.exclusions: |
      - apiGroups:
        - "tekton.dev/v1beta1"
        kinds:
        - "PipelineRun"
        - "TaskRun"
        clusters:
        - "*"

argo_rbac_cm: |
  data:
    policy.csv: |
      p, role:argocd-admin, certificates, get, *, allow
      p, role:argocd-admin, certificates, create, *, allow
      p, role:argocd-admin, certificates, update, *, allow
      p, role:argocd-admin, clusters, get, *, allow
      p, role:argocd-admin, clusters, create, *, allow
      p, role:argocd-admin, clusters, update, *, allow
      p, role:argocd-admin, repositories, get, *, allow
      p, role:argocd-admin, repositories, create, *, allow
      p, role:argocd-admin, repositories, update, *, allow
      p, role:argocd-admin, projects, get, *, allow
      p, role:argocd-admin, projects, create, *, allow
      p, role:argocd-admin, projects, update, *, allow
      p, role:argocd-admin, accounts, get, *, allow
      p, role:argocd-admin, accounts, update, *, allow

      p, role:thoth-admin, applications, get, thoth/*, allow
      p, role:thoth-admin, applications, create, thoth/*, allow
      p, role:thoth-admin, applications, update, thoth/*, allow
      p, role:thoth-admin, applications, delete, thoth/*, allow
      p, role:thoth-admin, applications, sync, thoth/*, allow
      p, role:thoth-admin, applications, override, thoth/*, allow
      p, role:thoth-admin, applications, action/*, thoth/*, allow
      g, aicoe-thoth-devops, role:argocd-admin
      g, aicoe-thoth-devops, role:thoth-admin

      p, role:data-hub-admin, applications, get, data-hub/*, allow
      p, role:data-hub-admin, applications, create, data-hub/*, allow
      p, role:data-hub-admin, applications, update, data-hub/*, allow
      p, role:data-hub-admin, applications, delete, data-hub/*, allow
      p, role:data-hub-admin, applications, sync, data-hub/*, allow
      p, role:data-hub-admin, applications, override, data-hub/*, allow
      p, role:data-hub-admin, applications, action/*, data-hub/*, allow
      g, data-hub-openshift-admins, role:argocd-admin
      g, data-hub-openshift-admins, role:data-hub-admin
