apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-dex-server
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.aicoe-argocd: https://argocd-server-aicoe-argocd.apps.ocp.prod.psi.redhat.com/api/dex/callback
