apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-sme-mailing-list-analysis
spec:
  destination:
    namespace: aiops-prod-argo
    server: https://api.ocp.prod.psi.redhat.com:6443
  project: aiops
  source:
    path: manifests
    repoURL: https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
