apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-sme-mailing-list-analysis
spec:
  destination:
    namespace: dh-stage-argo
    server: https://paas.stage.psi.redhat.com:443
  project: aiops
  source:
    path: manifests
    repoURL: https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
