apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solgate
spec:
  destination:
    namespace: aiops-prod-argo
    server: https://api.ocp4.prod.psi.redhat.com:6443
  project: aiops
  source:
    path: manifests/overlays/prod
    repoURL: https://github.com/aicoe-aiops/sync-pipelines.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
