apiVersion: v1
kind: Secret
metadata:
    name: api.rhods-idh.dev.datahub.redhat.com
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: api.rhods-idh.dev.datahub.redhat.com
    config: ENC[AES256_GCM,data:iu/wBkISd9kuN9WweqDRBFysXIjaORO8QnkOrmldGHv+q00v1e+78DogThWy1NCXrA9ZaAQvaRFWLJy0AstH/Iu4DAgUrt2YlwOIKJuHrkUkJqYZHp4JtlO8JeJd2G4ToL0olmVVe4OqvdAmQVp9tnjX0l0W3zy6lsE4TUxBWJxBE7ZXwdMMD0gS2k9vriGlZlSsSMtj5spyQzTjT47rnW2NYRZFoERf985weTO1JGrfVrwyzkDWqimJ0DHhFosl5Snt09Ar1Wwt/Zd0by3Mo60FVQZk86Hy+PziXcvMNRD9LYBDR4fG6amyPY9nYsFy71VcUSyJkP5HWeYxXndREynsCgA+HlOtJJXw/1Qm1cRV0FD6LQIaiBuf6GdM1/SPSqdt87xfH8Ka7IMbUIXUpDqn6rMOIsyca7xFec5PeG0imwUZ2Xevk9aHybzYeKRjfCbcHzQrakKrZ3Q69R3nZ8S/x6SgGbWMQw/cV930JaeIvfMjlEg+4bJvc6YIyRLrGzbM5jbjaGP5SuBnnsRU2NJ2tlJriSyEuDW7wJv0MJ1yuE2cL74hejcbKvO3spLwpBpv26jzLhKT8FDFVDVdMagFBkVFajJYpRQdlQmJwKkbCUxTZmWUzLfGyU2NKEtl79KZbmd5IjMUnwOQTqksrfxhdJAH33xRjvLNNDgTRuI5LBiX5i87CY2PRvS0uQqjLqYnlnLnRiPS8eFJBDYKvz97R1I98iXfZfFCKjmx9YOJlKOZJNjt8j5wYBD4oybN1qM1k7jz/qN5XypBYqeawI9K82bXiAmwG7GIU/J5RHpMDQVL6r6xCnX8yfM8xHQ8IuJfYD4jA1A0n33zIrReKeM1cgJt/jxax1pmtllS/X8pwnDfmTusda9wY/uR583MH9fxAbgk/V0Ma2WZpqIRiwnIVR59asCfTXdj2XtUiIH4e0Y0AXSAKaJDCc6f90e8K1gcc3XzossQK8JxblePFPVe27BVeeBR5xiPFNBKuTjtPZHXc/nd1fCQ6ZRKuQeqUGc2vkk0mu6zeqDRuOFEwAUwFalLIT8mFcXyZ7P8GN1OMRccjIzYwmD76pJdPvRY2WPekLE3hd1J6WIn3ePjYcHoPzV0Ci0u75vFOznzz3iEN4Pz01FIte1FD1kbsTxma4VHscXqCqX2zAtCYAF268IuG7HTJgLFmCaftjFd1zq6EbqdNJEx7D+gTzOa3L3xP/CjESd5RuHV+Zp+HSKMPby1zguO1zelLIdYeaYvq49ASltwXPUSeQG+tXgJXYn4gz+ULTSdpspFPkMkmlnpwQirOYTxsmcTFOKA9zIwC64z3h/DE6zJ16go0k3o,iv:HAdia7FqGphOZIj4+SnlNrxbKzduLYqWJpRkhJKowGk=,tag:nBJA79NG4C7C4Qjv4+DFAw==,type:str]
    namespaces: openshift-marketplace,redhat-ods-operator
    server: https://api.rhods-idh.dev.datahub.redhat.com:6443
    shard: "0"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-19T20:17:07Z'
    mac: ENC[AES256_GCM,data:x6iutPuOcEnNIK0GNUqBkg4A/65b7xeL1foxf+sWrGRZVwtTYAW8GSShVEMOvn17sDSOusDfmJFpe1Z4QXFy1N7k5UKL5HGwFsN6RTtJYzrGZq/gexgFRp6NtyJqOH8mGQO/oFrYPDuNMMWTA6Hm6KEAmd2S22xnQb4HzUSI0rs=,iv:+A6k3GGVkG30UHEqlTU/YmmexDhCjbObG5vB/2cC6oE=,tag:sfx83Au7L26t5zvGrC36Bw==,type:str]
    pgp:
    -   created_at: '2021-03-19T20:17:04Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+J0IzOZOodA5YDjkjEKrDZ7/FaIDwIxFj5yeMdb3pwpUF
            5zpcPPzMvxk1TnFayIqokxRVZ2qmWSjavMZ8N25KBkyTGXhSbvnrPkGnBQ37MsQZ
            OvSKwyfmKAAdHvACKm8xElbmoKAaW36fO1rGa/lPnqfvWhgkyc3Ran8gQQJOteNt
            HtF8B+NNLXcOnzzI6KGceGIzHjWB7tXC5ad1flxr+19g3fM+tef49pz1BxRB9TuF
            JQkyaL3nnnT5NOnCvcmrJhHZWPlZhlYhRJZXQvRsLzHHePcxJ0V5gh0HOyxwZCTH
            LM8i2EDuSBZD08M9zHXbt5sgs0oawUfJNi29XP2TxtJeASqIp5UW/kCfzB8YiQh1
            HxGgxsX5bVLKGczJPw/y1w/8DUJT73x28Vu2lPsDqzUoJPk5Yl1ST76sZn+KqH/I
            A4DAZG7Fjxb78Pj7ALsG1nruGLczOiGfmY1oGkIkkQ==
            =88DM
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(config)$
    version: 3.6.1
