apiVersion: v1
kind: Secret
metadata:
    name: cluster-api.ocp4.prod.psi.redhat.com
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: api.ocp4.prod.psi.redhat.com
    config: ENC[AES256_GCM,data:BcvOIJmJlFnN0n7QkIbfXe98SNU/n6FrE3V3CqsJ1YlI+MGafjkhzfycx4TnMnRTVc4elN1kR88yJAwX1wrNQtl0YdzB26AlwSW6lqljuSSgaSyR0lDD0tqLDv0si/crpHfQCQQdFsqnIvXNNeo43RaJH72Oddu0wxt2vcXFnUwSS65sxA5qS9HCQJZA3xFglEmwFeSUnHooeSaVdI5Yt1IbhpFlA/r5zczStl2mbxg+cyEyWXAtzKc7N4XKWsx1V6RLfAiuHe6Elb7HINzPG9M249k3DRi3U0FnzBopPhwvGu94RCs6WBz6gn2/+aulqRl+9nE6TQGg+W1v1YozG+rdTbdBycCb6XZm5L6YiX2SI84GMDvfrDashevtsYJh1Izgy81oZ7Yb5UZmzqzCfDkzVFb4xmkKL23YSlBlSOYgP8O6lnmloP42/+Qr/dkqrHAqm7EmjuzUt2wtzJHvXUkQFuApHLz1FFee3XxiqQvVYSSzDJKWk/TO1W2jqZ41bfAfi/b8sUr/YV9hHdW0KtWnm/mV1Zd/78EAHg9oAth/dMaBCuxnTlCvTbBx/35nMknbEzMeCcQFiM8a7f/vOYrtMjsVQi7eudtd3RDEyDE0Kg6o+avxoUi3nLpHuhd3zL3/+3fz1q6H6Qo6WsxzzTxfzW8uPxr/tJhvpqNWtWMdOKta8qNEuv+HbUQFhTtG2QbTZcmTCcSlwNmnbq2+aJDq0Nhf1t+dP+AHBPWRrNkTW2nF/YsaMVk3MAP4BrU07xoNWSXOdj785Itv0gE63lAWn4X3/RGix0V0Xiwsli+kk1V98Cw3nO+qwlv8ZwEmQHLgOp6TKyTx70uRJz0SI/2TcphTd2BgQcsEvp1h2qH+VoPDxJQ66sx+fSbJldEuSJoNDiFfnY3+lUrGQY6pV72pMEJ3EhQCs1f5x7CoWQbx2//9Mf317mmSvV5UdsK0QeeNmNbOjGBnFdasvEpuxO4grtkZLFELWzPm0cwG0wqVl2rG0D/Zp718lUtSL7ScVTy1ghw81UbfBtuc84uqBLOVpMjwp2Ve6igC0GSx+x7QglbcepTNnxuNxwCFTlKaR7V3nxZHwqNWWl6S/lrz34m18f8wv7ZE81UVQXNNGqATNQ3TiCTzJuuKpsuFcn9vafYsSVhrtUKMAfXDmr7DSocIQ4EzKmG2u6rbJDM3g5PBBpBdCp/rIcxvC9lptz9dxyAhNivmC5c42sHg7BGWhaJdxf50hlgvdDB7M0NYrT9wLGLqGfCN2si+xutSIOvT2dvRL9qLtWVdTs/PlEErP8L8iFSFWeakpTBIxgf4TZ3OA47uHzsOxQ==,iv:Rsz82upuC5Pa9YLgJ/AI/GJAXy3NQj/KHMXilWWip68=,tag:VHTxltUXiherPIuCtTESUg==,type:str]
    namespaces: aicoe-argocd,dh-psi-monitoring,dtuchyna-thoth-dev,fpokorny-thoth-dev,kpostlet-thoth-dev,thoth-amun-api-stage,thoth-amun-inspection-stage,thoth-backend-stage,thoth-frontend-stage,thoth-graph-stage,thoth-infra-stage,thoth-middletier-stage,thoth-test-core,aicoe-prod-bots,aicoe-infra-prod
    server: https://api.ocp4.prod.psi.redhat.com:6443
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-08T14:04:25Z'
    mac: ENC[AES256_GCM,data:XSwRx7xwCOCn5UycO0hICFiOszbzKYrAReJTJ1riol8zzOf1X6Gufl7LLD3iTEjTxSpj51JUi1Eu6rh2QPlgfg0FTcrrWxjmQ9GIRjmPDtSlv8ELJxwXjp8jmtMQ8HBPpj3jAwHl9kLsHcgUSBi1IDG21/A6IUR8S3BrUSxkCF8=,iv:GzOfEpNqWSz94bzMarnecjlQEw9JH9mE4Yk0spzBhUE=,tag:R7B+0w91saGDhQoZ/U3xqg==,type:str]
    pgp:
    -   created_at: '2020-09-23T16:32:13Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+KQsxIPlocbHQIJeXhtU0NWQPU7Yl/LfFLIbxvud00KMM
            kUZNwTfSTA+fan2iYsShGBO9Y5qwquvapkueaxeyOFeqan9OId9FG8xe8MU+YPMv
            7KSIOTxcz06R6O5vYiow+v6SrO805Dltx6SHYc9CNV2gB+SfEG0mj2IRTTISzZQs
            v6ZMk+LLyHFEaS7oDoXurYV+8EPSjvAs6/SooJMZd31GXxwxlFF7mrpJKO6utHW9
            Z0BXlg8ROQ3bLYg7zHW99/HMlwTF7FRT78NPWIauTnF3UcajQE07axmHk0qIajRZ
            6jYudlugAhjpiXQd1jAUz0WFMqEowbFflF09bGJl/9JcAbbghHielq5C/BxPttTk
            ywf5qn9+HPgVJFJ338tbXD2rkC+4b+eunuApOzmB5Y/nsIlAZTQkKsFp8yoWozSO
            FV/rYh233NMh1D0IhbaVe1UMlWeWB5ER4N1nRuc=
            =aR0E
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(config)$
    version: 3.6.0
