apiVersion: v1
kind: Secret
metadata:
    name: api.rhods-idh.dev.datahub.redhat.com
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: api.rhods-idh.dev.datahub.redhat.com
    config: ENC[AES256_GCM,data:hsh9cGMxiYIKrCkJ5xsGrTMhPwtFHqjSCYrwpu+cTmSxIfMbolGHae69e0k6akB5Xh7cqrY9dFJtSv52PA91UZqcYf366gqM3zRvENJFW4fEhm+1cyppI2IRzRLtppMqqPEn+YuVLAeB3Rqo3wKaHbocK1zavR5e54u0D+6AvWdQXaAJ9x//6TGwpboOxaIxnAE/lVraALuhlGcWW2ja6sna2bmqSxh6/YOXRplvrkpUBTpGjM+MhNEs/JDGlloXq3GZ18XmWLdCKd7UR6oRh50Va8nSVktNptQuZsN/Pr77Ig5APJX+YdOG3+sgF+f7/RsS4hv3nL2Dok+UQCuMBMw7IoJJbv8rRNZ4RghXojhuHr83O6iNIM9PnHkLe23lzUVv/efQLkxKz5Ghq+/+qyxItYqw96G0FnGA1e7oKX1jFSFEFkEG0kGsN74i5lGMTJse1TMBqy8vXSaANtMPFT69okUy+UJXVxuZ/pKNAq4lG88gInLegqv/xshQkpZhSTRNgAaSfMW2lB11BVajZjSTddIsC7+xXgUBpWjlLNLO3vYDe8OcwPW+HsV7HR1/y5gUPDhBtPtS6AAGdMoCLEakL+9VYilxSnJKtMeZE9J8BssNJaNMF/1cWGWaYoNn7ziQ+CzoZZn52WdvnuSCa0RO9FOp1bxSU+CIDzU0UA7A4C3k2Xp3FlsY6RXnZ9axwvXL4L/HeBB6qmwzH83bqhfGlEnO5he2HeK/I9pfbb5KAcROpq2rQys06L83Mza92HCu3ci6zZd1s8Vi8TFv9kZvXdh8NVTV6i7QGvInbTWp725CmQNS6y8dnO63oEab3ALtmtgvXSI6P3EKDHaVNnVQtxCCnfCU9jupKE/Cg+jITpKLwj+m86ODRBcfwzLjnQNSG+w3prjAsN94M/t/m/N/CHKx5Tm2XkHNZY6DKypBTBrBXzGxWVl5M+boZlVqH/BswfBbNghKR+bQrxuObM+F6nGP2918dCDdJxVdX3HLmczK0i6bkn1LSk9RtTn5FnQX/T3Jdpyb8gbGkQgMTBfD/McNf+ivBoLB4oJeW88oL/TeUXcZZdaa18SsNzSqksJgkEwhPlUP8HSuB0jNtUACOn5i1oKixRXDYa3qw8FtS2APFqWl2J9jA0rTJpt6x2czNhroQcKHHn6DsITFYC3f79EbwjUKM1OZcc02ZznuNGeU6sBNWRZ+OK8aKnrFc6FFUJk+Zvbqqp3GfadylYZ1subWFiwig3n9Cm9LDHZxwsnrbpxvMi0X0ftM2N7rZkAWKbr5549cCBgV81XWIe4W4jM/Jr4rdj5p2yyi7gnUsASH5jBX6ULE+Bfk,iv:mltcJK/d3MSwQOE3ZdsJUqLpq3INw+lI3JwVVBegHKs=,tag:GID5sxsGeIf/qReSXCQl1g==,type:str]
    namespaces: openshift-marketplace,redhat-ods-operator,redhat-ods-monitoring,redhat-ods-applications,dh-stage-trino,dh-stage-message-bus,dh-stage-telemetry-grafana,dh-stage-superset
    server: https://api.rhods-idh.dev.datahub.redhat.com:6443
    shard: "0"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-04T01:01:29Z"
    mac: ENC[AES256_GCM,data:SYiZuxrG67i6yDUxgmgtic3oozC5K4howmcxXWl9gs4nhx3sCq4CJ9Qz9jYiG0HbFk/9vAK0E73cUC4Jn+Ri6AfYdNDDKhxf/EQKq/RUs4d6ndwox+o9eK14s9gOjh9XmupOSAZVGz106beAwAl+DIIk8NPWYkbD3BJxk4vf4g0=,iv:83apCgrgVjmnwSUXivwKIcXrNBKBQdIavVBzpV9m3Us=,tag:x7muMlR6X8Uw/kP6gwK+mg==,type:str]
    pgp:
        - created_at: "2021-10-11T17:13:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf9GnRk/OWlM5hsQhWCk6hrGhBvMrFTGuvSg8yQOA1L6lLE
            fVKLMaH7hDMDHtaud7UMBIiaaIsAbsGz918IGVjdIKxLVzcNKaa5azFwsAGVj+th
            3plvM8DSbQ+2Emd8fQJ+lhhe1wYRkA2/6b42gUkOMcvBzK2Kn117CAsUtWBpMKlT
            1/wIkCo5cRpYYC2JrnQDfC/kuN0loc18Ll6eW2Cvpr8PSqqa1oiDExJqBxQds8Ta
            /hBd7thaCE/5xTip1kwQMkPPOE+Ql7c+93lPz9D2o8+Gul58rdmq0S3aPOYxK85o
            FgdlcMRi/HSAgizj+OiYWFT5bY9g5CoHzVIlvw616NJcAbcK56U1TyFrKwDV6aPX
            EbNxf/RPCFtExHFvjQVPpZDHUngV+ohykzgqetMuLZyCMGDXpAeZ4zFVgEauC2xr
            IiCfYykj+KMmBeviJOPiSATnoBqZuHUdXOXur9I=
            =XMpp
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(config)$
    version: 3.7.1
