apiVersion: v1
kind: Secret
metadata:
    name: cluster-datahub-ocp4.psi.redhat.com
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: datahub-ocp4.psi.redhat.com
    config: ENC[AES256_GCM,data:e+OKpwJnm2Th/Z7GI+BCUKf2WqBlRfuBjbxObwerEwdO7sobGBgmsIUA4XIY0oSkOIjoDDu6W+Cj171GCjMpJ3aKX12LpYaw2bjtZxec97jE0lMdHGr/ExwLL/R+aM/uOMMjMpDSROT68VnH1ROcCwrZFiAVFPLnlOmkCYaPtVvW5ONw3lezsS3USNl47jxuCLsO/PfeysUuL8GeSboG5+u2ovDCphnyOyWaAqh4GACxO7mtceKSpSqo/7AMFNLNdyFPueGPvOeMew53pIQ3+lX0igwVskeqDhrV0trrnnie/kG6P6h66neZV2ZAuCcD7W/9SVBPJCS8wGe88J9+iGTZwZbl8SoNEKb/IJcZS+54T0At0FErMGWKFwpY6mVpS+OdPKqtgUF8WdTzHn1G1994963hAXMCtPMAaklv2bq65SCDXrHCaGWQ3dOvcmBOvRY9QlRM8SbOKxmZoE/YthIwseqthi5ZavwNZurQnEq6xRfmMkZzmffXjzMxbMt4yOnpROTG/oxcp7JXdM9QScNS20LOI30sypptzCZUtbL9KG4mcUKJaAH3bKm66saEDAkguTmZ2vRb8n2taQa0p2OJmOBDHyvmdA3IQ2bZ07ZQDyjJtRuYyT0BX+qfaQqDatebLhC4feQ+z/dSnu41UXq9rOZriK/L/wRoBssNKjDD0xQobwFBf564YWy8mPIyMezfxadDVEcvwIUMWkma3jRUZTZAreve+Gv47S5ZKSji4wiSeiAs8RnNf1+cgqdxAvVvB8IO7T/h3BOZfJ5SiTEc/Yqte9siyf21awIDDvnXMmBgsBeF+RyllB1bldOxVLrQqbqQg/1P4WsDNFllCUhUj6CkbCmepdN6SSAcBqRU4rCOk+TC7lIwCA27VCiz69m0ynrM/C3JNcQIjZIAL5wXkwzqvzpnV87BTQ1qbazHkFgxeNDxUEl7SNRRmq3Mp4G3hpfQMc9uaFdV9AlYpB1RA/Pl01nVLOsmQbBUVFNe5YUNQo5xdYE/Pk08ZxlMU6sdLvFEnjpb7X5d07TsIJMfJgoR6U7qi4cehk4jMHLeyXana9D++1snhza3uE/5AHZGoAs+O59/JjmR3Nikn64LTGYJCfYb/4KN6wQKiBwEm9ckSIR49Jq6xF2Lp3jBxHbnzsccQ+FjD56eBHw/0tPwJZvI/dJ77n4h9eBvLhd78DRfn8iDIT8Yz7VSId1142i2rNIpYidB4pWplp12ONVQl93d6hFRZTrLCrd7et0sAZEW13Ms+CsWEO5NECyUVJDBzs2dFg7dd8R/r46grpO7Y5O65kIqOaV2bieTPSKnaFtFCRTeYZlpkRgVWBPf1KfFDlw6AZANs3oviSWK1OLEvtMIIWFnXo23I8VSqpBqv3YFUMFA3mIE/uSpybZVUnwQmklj4fPqaxldyxgfREAMmPZrZWIXI8S3IzeWd1HFIEH7xflY0hB0/CQ4iZyPxMRQK+T9Axe5y8DNRVjrRqY01KEtXHTN+Ijy56xO12Sc3cJg2lDqoW7mU+IAKmcBE732W7HZ0TvEPIhbJGBtypK+nbik9FGbMmrjNttJZm+g12MRRcJCZB8ylFnLizcxU8qRYlMn8uv0wrUeXafmbyuBPNB9P4ESQYF41/a1N4TOP/mN5eJ5c0KVHQEwECuXEQ/T7mfleN1yAUonmusBCPskPhPkqmybkp72K8tVLlaPypRDAipQhc83h932vw7Yz+U/Md9fHCR6yWrgztPduY5N3UwSmmG4rmr46pdTb41Hl7VZhRndVD415LX5XLfleNI=,iv:UCDrFiIiGjM/BrD475QJq4pgXdOAGGQKeB2zISdnLcQ=,tag:WzgiGaVX7H9+MIZMn4pRNg==,type:str]
    namespaces: argocd-manager,dh-prod-argo,dh-prod-thanos-extractor,redhat-ods-applications,redhat-ods-monitoring,redhat-ods-operator,dh-sandbox-telemetry-grafana,dh-prod-telemetry-grafana,dh-prod-trino,dh-prod-docs
    server: https://api.datahub-ocp4.prod.psi.redhat.com:6443
    shard: "0"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-11-10T13:52:42Z'
    mac: ENC[AES256_GCM,data:Y90Dy53AGZeLzj6W5GIiblrkxZnI2QPjeeqZmmEbdHXTHYJmGwAZamP+G8HEY1JOOabCkdHJmJLDsfo2hi2VON40zO97QRXFANYUnwLxz2+GY/49kq9cYc1x9cWnniHk4DFtIbFHaaHopyEwKZKsAc7jh4j1xvK/jy2m10zwLm4=,iv:lZjrmn545cCPvgbrcZoMhnWpvJGu00hfpvtObhmxSuM=,tag:xJRjIuM8C13QMQcpgIqA1w==,type:str]
    pgp:
    -   created_at: '2021-10-12T19:28:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+JKj/80FXbJ4UPP6evIrxd9Q89jwlXbFyXa6g2/sW7uz2
            z71L0c2fP5HtlOnCQcAI48fHTieFh7+Bi5bbpYj7Z0mHxeIFsmtc0/4G/Qo8z8h9
            KthBHbD0dSx2Uu+YazX78/8lrG96K8PIRf3GgQY7zPJaniYTAujRcduR20BcpSwc
            /YBo8v0MIvoU+P1TBIuL8ThAbDYnQHRoHstn5vuLbIdssxVdiCjYPKqC/rlJ/zV5
            iuWVA7mazI2u8mnhVyppO7gqlb1AH+35HTwtugnmof2MHmcu6+uE2x5cjqzj4cQr
            7rCQ+DQ9j/svnHa8sNAeLgDU+qM4gxD81/R75mDNidJeAQde54fEN9tW93a4uu7l
            69uF/4Jf1gtuU/K1sjN0wAz1iibxOLnmGjVVaGiWUH8UYEUw3sqtdezYkUEHpuEu
            z4ys2DhlpBazl0NCIgZSvZqD2j06mKBl0jotCRJ7Sw==
            =HXKI
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(config)$
    version: 3.7.1
