apiVersion: v1
kind: Secret
metadata:
    name: api.idh-stage.dev.datahub.redhat.com
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:oSUUUkkR57YwxUo2p0VDj/vfW/8oa3bkwoB9hOmWvfvZf5Qm,iv:8wpi1OWw/31uBaOJ1jQsf5j2nD/5kg81DzSGq9wSQaA=,tag:sVhlucyI+tszfqsAGoLMaA==,type:str]
    config: ENC[AES256_GCM,data:ynyqDpo1hHHBg6fPU805gLMq5TaL426yNvWHAZK4kZmUQDi4WCU+BB2DxfGXojcq71Z+4YBLZz+kDs+Bn3cmx+16vsFLFH9VsM99SX72s9kOZQNnLBJwjdNoiO+slw5PlRNoPjcOyQpzE4E4T15ttDVIbVI+Elr2mV148wLyQdWBcQ5+mP/4HF92v4RRyTYVIrRs2MaeAyd4Ba7MqgcaqJy1PZGqbK3wRlUaO2VOFCT05D4cWaXGCq2W/VxboOktTdPYqnjaYbl31ZSGCNHRTMDhEsSnU9hhCLdKx7S5x1bpjLC/x2eE1mqRp4Pp2qllyV7+B4WEAXuBRz+q1j9NWeJKroZiGKTr58dGgl+alNPQuidSezhPbUOpEsmELKu5RYce8StLYgL1nBswEMnMqA8kG3V7BRxKuxGBa9F/8M0+sIKtKoxNz88KkFrGTDl2PCGOb3A62/oDKgEz1tQ/GGN2g1YgUfDT/o8B6hK4Thw4Z9Oxnzhn/c1n/rWSWsEhWz1lI6sNlQyOC3F3RBZKinsOyA4LFxKquicuMAk+RhS59Cr77+hrPPu+KST8ETY8JCbugonQEZzamoFcWPD5rQ/cI5F3M/SV7BPIMScE32mtZ/bk6YAci64YYXusiqcyQ3bF4pX1p/Mi7LDv8/jOyJ830kH3VZ87Cef1vBmMyTkhPo26GWGhFaRlYzVh9hvlRMaOb9kP5kY19xnA61oNe45ldafIj5AxaYpdOBC+MPjFWPNTNxH5nwn5Ts7MSXnf82SJLlOw/jz2bbcqgak6tC3Ap5dccajWnnNCrbEXx41f8IVaOYGAbe86hR94juzTMxCMdxZTqBX1UBeeFgf4o9+Ur5tBzkO7nLHQHS49Ejd1Y42/sp+X4vt5Ge5EM1rZmGdkXCNuWxSMc8I/IAhUZncmh/Tth0FmKDaXbkIpSQw4M06jDCWVcykrB+evxXADUks52u098NjBmVGTM2999YKxWwiG9B180a6/EILZuxwFV7T2TuBUvf07V+emUQgfdLPvxnqUJSdYlmP7RUBrW7Op7bdOHp42Cw8leJm6HDDmg1W3Ch0mxvmQ2qAMLlsuTNKY4I2+TN9k8L8iXHqdcg0gQIXUBuCRfai93g/vGnye3R7s5tK8DQJrtqsWiJE3GNYt2eWyIGJVhBtjfgf5bqs9Ey3XXsLdRUPCZK4Vxc2qz43bT8jntQu3ArVGZzHAFUusUH0wDdEutZtFmwIddaCdhZrTVY1ucYP4vrSxrHFcHKDVlVQZHFeuaduXfcSO4rQv3zQERKSrzKtIhzE+QShys5WJVI5wco0kvkmRYfoXdKiypSDPV9kAt/HPPZEEe0mup2UM5WL6aabE3lPEM6ISKQVMt/gcZ8OJk4ao0qEqWK/0VXmBwN9r+F99AUuBn0sSxIKJ347joP2e2blaisbnE2PSvEG40FM4+SA3wIuQdpaJMXUUo1YIUiaoOYV7NlO8swOS8u83Q9D4q7XFMKenCjf5kjt6ldh+HCJQOh8+8y7y+pmENFBxZ+RMe+XYh7b/ZbwyzAFxElwg8HRswQ0jNIPSEOl6ihG679huu3D6r8qw3NbLhIO9DtCPiOonrlPx2aXXbge5ilh6++O11neihI5wNksVxkOwJ06OG9lavuSCRdE2pAz4mLHMwpWKz6jASqtPhdTotWeBDMML9VeBaeXfxgUXc5iFfa7xWdaGMGygoncGt1I24VO2Ey9uoJhpnPNLswtIM7GDMPcSidhGJyq2UPHNidkSgRHB/LwQqRzH9gRkj6SBxCg6uhMZdbo=,iv:kBRYtGuN0ykx3RMCoREqA9SpSwwdxUsJcxIFHATT76Q=,tag:puSd9ByRax94uf2jRCHFCw==,type:str]
    namespaces: ENC[AES256_GCM,data:xuWBUPiwcT4IITHPIbAlCAk=,iv:awuihx3cu182K0eITuplDKmw6lC6zHrWxMFk9sThV/I=,tag:i6ewRo56D2h4J/VS2Kitmg==,type:str]
    server: ENC[AES256_GCM,data:REYSUDYsBs+Qw8Ojdei0woX+5yw/D7ZDWVxVYGFa7Zvva1q9HO64sONCcBuQKXS+/A==,iv:yYH4dnpKfOANEy3G3+bDN2YjCGRbDKEwt6MBeP4y28g=,tag:wqvJJ/mnKSZfCBeBF7zwJA==,type:str]
    shard: ENC[AES256_GCM,data:4A==,iv:Dy0nJWjUHaQiKcfbZCZiUrJN9pMDb2SqfG/QK2dzNY8=,tag:CF9b//egZoYG7aoXyKEzCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-12-21T17:21:41Z'
    mac: ENC[AES256_GCM,data:BXGETxv4i4dncSTXO0CrUb/aJOR2Pphb3weo8kNmIpAVJaj6arkFT+RG9hje71U8lhYFz8U9AP8QMJHd1TtLfcsfQih5D5k7gOQi5TEp8nbeIrAthLZ6ReMLWUCGJNRMZMTOQiJ/h9fjplD95RjkOKqJHYyYLJcEQ6Y5r7lr+IM=,iv:+BlGu/lxxdrGtDtU7uA40q/erYT9xJdglIozfLc5WNs=,tag:3CcIGjqsZzo8Y+u6h5htjQ==,type:str]
    pgp:
    -   created_at: '2021-12-21T17:21:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+PEknZMOAlWqYJCpJvotcu+KhStXfa/5okoVdtLL2rA5y
            rZM3gqzs/TAlI17IQb5foPKmWo3VhK9QqOt5W0TKVj5SZXC6BlDLf9tJJ7nvr56v
            0j8kCHFu08SGebRTFGEexNiUWmGhTrI35OwLoWKiaFTCHKSHMngvJ0OdKSiZ/SZm
            Vl1+O1EKI8rIuXR5sZzKHYsKQBd4ux4zprSGQcsgrBnqEpfnBQPzWlCa+qqEyODy
            Jgjen/JW9R/2zcJiu0T/vaPMhomPfOwlsxkS4S5LIdfK1OtAgLg7+391L7uUrrUl
            2nHe4DXBiusHsDWrf/BUleHeZZIB3IRvBkyOTT71KtJeASJhFNwXFKei8H2XI0uU
            IpjZAkRm6Kzo1otDDynr8tvGU3dxoJK4a9bqAhWJzDlVKsttAav9BgMYnRgAzdEi
            yovhsSb3jMN6ezhNNYnnTY0xoXh3Cv6KhQNCIABMHA==
            =cg/g
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
