apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cluster-spec-generator
files:
- secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
- secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
