---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-stage-thoth-core-frontend
spec:
  project: thoth-stage
  source:
    path: core/overlays/ocp4-stage/frontend-stage
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: thoth-frontend-stage
    server: "https://api.ocp4.prod.psi.redhat.com:6443"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
