---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-stage-thoth-core-middletier
spec:
  project: thoth-stage
  source:
    path: core/overlays/ocp4-stage/middletier-stage
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: thoth-middletier-stage
    server: "https://api.ocp4.prod.psi.redhat.com:6443"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argo-server
      jsonPointers:
        - /spec/template/spec/containers/0/image
