---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-stage-thoth-integration-tests
spec:
  project: thoth-stage
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: integration-tests/overlays/ocp4-stage
    targetRevision: master
  destination:
    server: 'https://api.ocp4.prod.psi.redhat.com:6443'
    namespace: thoth-infra-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=false
  ignoreDifferences:
  - group: batch
    kind: CronJob
    name: integration-tests
    jsonPointers:
    - /spec/jobTemplate/spec/template/spec/containers/0/image
