---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-stage-thoth-graph-sync-middletier
spec:
  project: thoth-stage
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: graph-sync/overlays/ocp4-stage/middletier
    targetRevision: master
  destination:
    server: 'https://api.ocp4.prod.psi.redhat.com:6443'
    namespace: thoth-middletier-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: template.openshift.io
      kind: Template
      name: graph-sync-job
      jsonPointers:
        - /metadata/labels
