---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-thoth-purge-job
spec:
  project: thoth-stage
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: purge-job/overlays/ocp4-stage
    targetRevision: master
  destination:
    server: 'https://api.ocp4.prod.psi.redhat.com:6443'
    namespace: thoth-middletier-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
