---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-stage-thoth-amun-inspection
spec:
  project: thoth-stage
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: amun/overlays/ocp4-stage/amun-inspection
    targetRevision: HEAD
  destination:
    server: 'https://api.ocp4.prod.psi.redhat.com:6443'
    namespace: thoth-amun-inspection-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argo-server
      jsonPointers:
        - /spec/template/spec/containers/0/image
