---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-thoth-core-graph
spec:
  project: thoth
  source:
    path: core/overlays/stage/graph-stage
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    targetRevision: master
  destination:
    namespace: thoth-graph-stage
    server: 'https://api.ocp.prod.psi.redhat.com:6443'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
