---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-thoth-graph-sync-backend
spec:
  project: thoth
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: graph-sync/overlays/stage
    targetRevision: master
  destination:
    server: 'https://api.ocp.prod.psi.redhat.com:6443'
    namespace: thoth-backend-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: template.openshift.io
      kind: Template
      name: graph-sync-job
      jsonPointers:
        - /metadata/labels
