---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-thoth-cve-update
spec:
  project: thoth
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: cve-update/overlays/stage
    targetRevision: master
  destination:
    server: 'https://api.ocp.prod.psi.redhat.com:6443'
    namespace: thoth-frontend-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
