---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-thoth-metrics-exporter
spec:
  project: thoth
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: metrics-exporter/overlays/stage
    targetRevision: HEAD
  destination:
    server: 'https://api.ocp.prod.psi.redhat.com:6443'
    namespace: thoth-infra-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
