apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prod-slo-reporter-aws.yaml
- prod-slo-reporter.yaml
- prod-thoth-integration-tests-aws.yaml
- prod-thoth-integration-tests.yaml
- prod-thoth-pulp-metrics-exporter.yaml
